#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#pkill -USR1 -x sxhkd
#bspc subscribe node_add | while read -a msg ; do
#    node_id=${msg[4]}
#    bspc node "$node_id" -t pseudo_tiled
#done
$HOME/.config/polybar/launch.sh &
numlockx &
feh --bg-fill $HOME/Imágenes/Fondos/Kraken.png &
killall picom ; picom --experimental-backend &
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6
bspc config border_width         2
bspc config window_gap           5
bspc config focused_border_color '#f7768e'
bspc config normal_border_color  '#12141d'
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
